#define VALID_PETAL_SCRIPT 0
#define INVALID_PETAL_STANZA_VER 1
#define INVALID_PETAL_STANZA_SEQ 2
#define INVALID_PETAL_STANZA_SID 3
#define INVALID_PETAL_STANZA_DID 4
#define INVALID_PETAL_SCRIPT 44

